site_name: JZW7258软件规格书
site_url: https://yanzhao.github.io/sw-spec
site_author: 技术文档团队

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
  palette:
    primary: teal
    accent: deep orange

nav:
  - 首页: index.md
  - 引言: sections/01-引言.md
  - 功能需求: sections/02-功能需求.md
  - 系统设计: sections/03-系统设计.md
  - 下载PDF: assets/spec.pdf

plugins:
  # - search
  # - plantuml:
  #     server: 'http://www.plantuml.com/plantuml'
  # - markdownextradata

extra_css:
  - css/custom.css