site_name: JZW7258软件规格书
site_url: https://yanzhao.github.io/sw-spec
site_author: 技术文档团队

theme:
  name: readthedocs
  #readthedocs # material #rtd-dropdown #ivory #gitbook
  custom_dir: overrides
  collapse_by_default: false
  highlightjs: true
  hljs_languages: 
    - yaml
    - django
  icon:
    logo: fontawesome/brands/telegram
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right

  features:
    # - navigation.tabs
    - navigation.top
    - content.code.copy
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    # - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    # - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开 
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - primary: green
    - accent: deep green
    - scheme: slate
  local: zh_CN 
    

# 航结构对象
nav:  
  - 首页: index.md
  - 产品介绍: #sections/产品介绍/产品介绍目录.md
      - 快速入门: sections/产品介绍/JZW7258_IDK使用介绍/01-01IDK快速入门.md
      - 成品展示: sections/产品介绍/成品展示.md
      # - JZW7258_AVDK使用说明: sections/产品介绍/JZW7258_AVDK使用介绍/02功能需求.md
  - 系统设计: #sections/03-系统设计.md
    - 软件架构与分层: sections/系统设计/02-01软件架构与分层.md
    - 硬件接口开发: sections/系统设计/02-02硬件接口开发.md
    - 屏幕接口开发: sections/系统设计/02-03屏幕接口开发.md
    - 应用开发: sections/系统设计/02-04应用开发.md
  - 下载PDF: 
    - assets/spec.pdf

plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - include-markdown
  # - mathjax
  # - i18n:
  #     default_language: zh
  #     languages:
  #       en: English
  #       fr: Français
  #       zh: zh_CN

  # - giscus:
  #     repo: username/repo
  #     repo_id: R_kgDOG12345
  #     category: Comments
  #     category_id: DIC_kwDOG12345
  #     mapping: pathname
  # - with-pdf:
      # copyright: jzw@2025
  #     cover_subtitle: v0.0.1
  #     author: mmx
  #     cover: true
  #     back_cover: true
  #     output: pdf/文件名称.pdf 
  # - plantuml:
  #     server: 'http://www.plantuml.com/plantuml'
  - markdownextradata
extra:
  version: 1.0
  # homepage: https://example.coms
extra_css:
  - override/css/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css


# google_analytics: ['UA-10006093-5', 'readthedocs.sheets.ch']